[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor = "AYJXLLzGihm83yZKH9TdzGffGS6H1Pkqu6p5vyW8bpiJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gabrielfior/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
